imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
# http://symfony.com/doc/current/reference/configuration/assetic.html
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ WorkshopTwitterBootstrapBundle, WorkshopMainBundle, WorkshopLessonOneBundle, WorkshopLessonTwoBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite:
            apply_to: "\.css$"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }



### added bundle configurations

# https://github.com/willdurand/BazingaFakerBundle
bazinga_faker:
    orm:      doctrine
    seed:     4535647456745
    locale:   de_DE
    entities:
        Workshop\LessonTwoBundle\Entity\BlogPost:
            custom_formatters:
                slug: { method: null }
                author: { method: name }
                title: { method: sentence, parameters: { nbWords: 3 } }
                abstract: { method: paragraph, parameters: { nbSentences: 3 } }
                content: { method: paragraph, parameters: { nbSentences: 15 }}

# https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/Resources/doc/index.rst
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true
            timestampable: true

# http://knpbundles.com/KnpLabs/KnpPaginatorBundle
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: WorkshopMainBundle::sliding.html.twig     # sliding pagination controls template
        sortable: WorkshopMainBundle::sortable.html.twig      # sort link template

# more bundle configuration here...