<?php

namespace Workshop\LessonTwoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Workshop\LessonTwoBundle\Entity\BlogPost;

/**
 * BlogPostCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostCommentRepository extends EntityRepository
{
	/**
	 * Creates a "defaulted" QueryBuilder used to fetch only "online" posts.
	 * Data will be sorted by created_at in descending order.
	 *
	 * @return \Doctrine\ORM\QueryBuilder
	 */
	private function createBaseQueryBuilder() {
		return $this
			->createQueryBuilder('bpc')
			->select('bpc')
			->where('bpc.isOnline = 1')
			->orderBy('bpc.createdAt', 'desc');
	}

	/**
	 * Creates a query used to paginate.
	 * @return \Doctrine\ORM\Query
	 */
	public function createPaginationQuery() {
		return $this
			->createBaseQueryBuilder()
			->getQuery();
	}


	/**
	 * Fetches all comments related to specific blog post.
	 * @param BlogPost $blogPost
	 * @return mixed
	 */
	public function findOnlineByBlogPost(BlogPost $blogPost) {
		return $this
			->createBaseQueryBuilder()
			->andWhere('bpc.blogPost = :blogPost')
			->getQuery()
			->setParameter('blogPost', $blogPost)
			->execute();
	}
}
